CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
CREATE UNIQUE INDEX `PRIMARY` ON `SportBook`.`eventos` (`id`);
CREATE INDEX `idx_eventos_nombre` ON `SportBook`.`eventos` (`nombre`);
CREATE INDEX `idx_eventos_fecha` ON `SportBook`.`eventos` (`fecha_evento`);
