INSERT INTO metadata.api_catalog (
    api_name,
    api_type,
    base_url,
    endpoint,
    http_method,
    auth_type,
    auth_config,
    target_db_engine,
    target_connection_string,
    target_schema,
    target_table,
    request_body,
    request_headers,
    query_params,
    status,
    active,
    sync_interval
) VALUES (
    'jsonplaceholder_users',
    'REST',
    'https://jsonplaceholder.typicode.com',
    '/users',
    'GET',
    'NONE',
    '{}'::jsonb,
    'PostgreSQL',
    'host=localhost port=5432 dbname=DataLake user=tomy.berrios password=Yucaquemada1',
    'api_data',
    'jsonplaceholder_users',
    NULL,
    '{}'::jsonb,
    '{}'::jsonb,
    'PENDING',
    true,
    3600
) ON CONFLICT (api_name) DO UPDATE SET
    base_url = EXCLUDED.base_url,
    endpoint = EXCLUDED.endpoint,
    active = EXCLUDED.active,
    updated_at = NOW();

